### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by CritFlaw** [beeshroom/Brickery#2]
In version 1.0 of the mod  and forge 2780, there is a server crash on startup
Crash log - https://hastebin.com/ajurukalul.rb

**Comment by JoelZBub** [comment]
Since the crash log in that hastebin has expired, I'll paste a new one to try to get a reply.
https://pastebin.com/2YnYKenF
Looks like client classes loading on the server side.

**Comment by DrakoAlcarus** [comment]
I'm getting the same issue, and I'm sure keeping the error log helps best. Here is what my server is reporting:

Basic Error:
[14:48:16] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@1d5f543:
java.lang.NoClassDefFoundError: net/minecraftforge/client/model/ModelLoader

<details>
[14:48:16] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@1d5f543:
java.lang.NoClassDefFoundError: net/minecraftforge/client/model/ModelLoader
        at com.beeshroom.brickery.blocks.BlockBase.register(BlockBase.java:31) ~[BlockBase.class:?]
        at com.beeshroom.brickery.blocks.BlockBase.<init>(BlockBase.java:23) ~[BlockBase.class:?]
        at com.beeshroom.brickery.blocks.BlockMossyBricks.<init>(BlockMossyBricks.java:11) ~[BlockMossyBricks.class:?]
        at com.beeshroom.brickery.init.ModBlocks.<clinit>(ModBlocks.java:32) ~[ModBlocks.class:?]
        at com.beeshroom.brickery.util.handlers.RegistryHandler.onBlockRegister(RegistryHandler.java:23) ~[RegistryHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_RegistryHandler_onBlockRegister_Register.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845) [GameData.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628) [Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) [nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.model.ModelLoader
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 16 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/ModelBakery
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.model.ModelBakery
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 16 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@15caf08 from coremod FMLCorePlugin
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 16 more
Caused by: java.lang.RuntimeException: Attempted to load class cgb for invalid side SERVER
        at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 16 more
[14:48:16] [Server thread/ERROR] [FML]: Index: 8 Listeners:
[14:48:16] [Server thread/ERROR] [FML]: 0: NORMAL
[14:48:16] [Server thread/ERROR] [FML]: 1: net.minecraftforge.fml.common.eventhandler.EventBus$1@27de5c
[14:48:16] [Server thread/ERROR] [FML]: 2: net.minecraftforge.fml.common.eventhandler.EventBus$1@14531d5
[14:48:16] [Server thread/ERROR] [FML]: 3: net.minecraftforge.fml.common.eventhandler.EventBus$1@c0e655
[14:48:16] [Server thread/ERROR] [FML]: 4: net.minecraftforge.fml.common.eventhandler.EventBus$1@1da4fb1
[14:48:16] [Server thread/ERROR] [FML]: 5: net.minecraftforge.fml.common.eventhandler.EventBus$1@109aa28
[14:48:16] [Server thread/ERROR] [FML]: 6: net.minecraftforge.fml.common.eventhandler.EventBus$1@16cf645
[14:48:16] [Server thread/ERROR] [FML]: 7: net.minecraftforge.fml.common.eventhandler.EventBus$1@8151b3
[14:48:16] [Server thread/ERROR] [FML]: 8: net.minecraftforge.fml.common.eventhandler.EventBus$1@18329d5
[14:48:16] [Server thread/ERROR] [FML]: 9: net.minecraftforge.fml.common.eventhandler.EventBus$1@1e797a7
[14:48:16] [Server thread/ERROR] [FML]: 10: net.minecraftforge.fml.common.eventhandler.EventBus$1@1819c00
[14:48:16] [Server thread/ERROR] [FML]: 11: net.minecraftforge.fml.common.eventhandler.EventBus$1@147454a
[14:48:16] [Server thread/ERROR] [FML]: 12: net.minecraftforge.fml.common.eventhandler.EventBus$1@1f60c76
[14:48:16] [Server thread/ERROR] [FML]: 13: net.minecraftforge.fml.common.eventhandler.EventBus$1@c9f380
[14:48:16] [Server thread/ERROR] [FML]: 14: net.minecraftforge.fml.common.eventhandler.EventBus$1@1450845
[14:48:16] [Server thread/ERROR] [FML]: 15: net.minecraftforge.fml.common.eventhandler.EventBus$1@396bf2
[14:48:16] [Server thread/ERROR] [FML]: 16: net.minecraftforge.fml.common.eventhandler.EventBus$1@14b5bff
[14:48:16] [Server thread/ERROR] [FML]: 17: net.minecraftforge.fml.common.eventhandler.EventBus$1@63f8a5
[14:48:16] [Server thread/ERROR] [FML]: 18: net.minecraftforge.fml.common.eventhandler.EventBus$1@193d54c
[14:48:16] [Server thread/ERROR] [FML]: 19: net.minecraftforge.fml.common.eventhandler.EventBus$1@f05c37
[14:48:16] [Server thread/ERROR] [FML]: 20: net.minecraftforge.fml.common.eventhandler.EventBus$1@1177fb5
[14:48:16] [Server thread/ERROR] [FML]: 21: net.minecraftforge.fml.common.eventhandler.EventBus$1@fa1362
[14:48:16] [Server thread/ERROR] [FML]: 22: net.minecraftforge.fml.common.eventhandler.EventBus$1@1fe8c44
[14:48:16] [Server thread/ERROR] [FML]: 23: net.minecraftforge.fml.common.eventhandler.EventBus$1@1cb6de8
[14:48:16] [Server thread/ERROR] [FML]: 24: net.minecraftforge.fml.common.eventhandler.EventBus$1@14f4073
[14:48:16] [Server thread/ERROR] [FML]: 25: net.minecraftforge.fml.common.eventhandler.EventBus$1@1603f3b
[14:48:16] [Server thread/ERROR] [FML]: 26: net.minecraftforge.fml.common.eventhandler.EventBus$1@ab1b3f
[14:48:16] [Server thread/ERROR] [FML]: 27: net.minecraftforge.fml.common.eventhandler.EventBus$1@d38cef
[14:48:16] [Server thread/ERROR] [FML]: 28: net.minecraftforge.fml.common.eventhandler.EventBus$1@10c1dde
[14:48:16] [Server thread/ERROR] [FML]: 29: net.minecraftforge.fml.common.eventhandler.EventBus$1@13374e3
[14:48:16] [Server thread/ERROR] [FML]: 30: net.minecraftforge.fml.common.eventhandler.EventBus$1@1e9e619
[14:48:16] [Server thread/ERROR] [FML]: 31: net.minecraftforge.fml.common.eventhandler.EventBus$1@1edb03f
[14:48:16] [Server thread/ERROR] [FML]: 32: net.minecraftforge.fml.common.eventhandler.EventBus$1@d0bf31
[14:48:16] [Server thread/ERROR] [FML]: 33: net.minecraftforge.fml.common.eventhandler.EventBus$1@c65c64
[14:48:16] [Server thread/ERROR] [FML]: 34: net.minecraftforge.fml.common.eventhandler.EventBus$1@e1a0cb
[14:48:16] [Server thread/ERROR] [FML]: 35: net.minecraftforge.fml.common.eventhandler.EventBus$1@e190e0
[14:48:16] [Server thread/ERROR] [FML]: 36: net.minecraftforge.fml.common.eventhandler.EventBus$1@193973a
[14:48:16] [Server thread/ERROR] [FML]: 37: net.minecraftforge.fml.common.eventhandler.EventBus$1@1d8dc90
[14:48:16] [Server thread/ERROR] [FML]: 38: net.minecraftforge.fml.common.eventhandler.EventBus$1@90dcd8
[14:48:16] [Server thread/ERROR] [FML]: 39: net.minecraftforge.fml.common.eventhandler.EventBus$1@34203a
[14:48:16] [Server thread/ERROR] [FML]: 40: net.minecraftforge.fml.common.eventhandler.EventBus$1@1175f81
[14:48:16] [Server thread/ERROR] [FML]: 41: net.minecraftforge.fml.common.eventhandler.EventBus$1@162caf
[14:48:16] [Server thread/ERROR] [FML]: 42: net.minecraftforge.fml.common.eventhandler.EventBus$1@b25229
[14:48:16] [Server thread/ERROR] [FML]: 43: net.minecraftforge.fml.common.eventhandler.EventBus$1@1b099f5
[14:48:16] [Server thread/ERROR] [FML]: 44: net.minecraftforge.fml.common.eventhandler.EventBus$1@7e2dd5
[14:48:16] [Server thread/ERROR] [FML]: 45: net.minecraftforge.fml.common.eventhandler.EventBus$1@11e0661
[14:48:16] [Server thread/ERROR] [FML]: 46: net.minecraftforge.fml.common.eventhandler.EventBus$1@1df3171
[14:48:16] [Server thread/ERROR] [FML]: 47: net.minecraftforge.fml.common.eventhandler.EventBus$1@636dce
[14:48:16] [Server thread/ERROR] [FML]: 48: net.minecraftforge.fml.common.eventhandler.EventBus$1@1e0f292
[14:48:16] [Server thread/ERROR] [FML]: 49: net.minecraftforge.fml.common.eventhandler.EventBus$1@4cc981
[14:48:16] [Server thread/ERROR] [FML]: 50: net.minecraftforge.fml.common.eventhandler.EventBus$1@722c00
[14:48:16] [Server thread/ERROR] [FML]: 51: net.minecraftforge.fml.common.eventhandler.EventBus$1@13439dd
[14:48:16] [Server thread/ERROR] [FML]: 52: net.minecraftforge.fml.common.eventhandler.EventBus$1@184234b
[14:48:16] [Server thread/ERROR] [FML]: 53: net.minecraftforge.fml.common.eventhandler.EventBus$1@1a0f6fb
[14:48:16] [Server thread/ERROR] [FML]: 54: net.minecraftforge.fml.common.eventhandler.EventBus$1@bd8a3
[14:48:16] [Server thread/ERROR] [FML]: 55: net.minecraftforge.fml.common.eventhandler.EventBus$1@33f4ee
[14:48:16] [Server thread/ERROR] [FML]: 56: net.minecraftforge.fml.common.eventhandler.EventBus$1@2b0ed8
[14:48:16] [Server thread/ERROR] [FML]: 57: net.minecraftforge.fml.common.eventhandler.EventBus$1@b838c8
[14:48:16] [Server thread/ERROR] [FML]: 58: net.minecraftforge.fml.common.eventhandler.EventBus$1@1229fc
[14:48:16] [Server thread/ERROR] [FML]: 59: net.minecraftforge.fml.common.eventhandler.EventBus$1@1e12a54
[14:48:16] [Server thread/ERROR] [FML]: 60: net.minecraftforge.fml.common.eventhandler.EventBus$1@19aa67e
[14:48:16] [Server thread/ERROR] [FML]: 61: net.minecraftforge.fml.common.eventhandler.EventBus$1@dfbb3d
[14:48:16] [Server thread/ERROR] [FML]: 62: net.minecraftforge.fml.common.eventhandler.EventBus$1@18d3393
[14:48:16] [Server thread/ERROR] [FML]: 63: net.minecraftforge.fml.common.eventhandler.EventBus$1@1ce173c
[14:48:16] [Server thread/ERROR] [FML]: 64: net.minecraftforge.fml.common.eventhandler.EventBus$1@16deb6d
[14:48:16] [Server thread/ERROR] [FML]: 65: net.minecraftforge.fml.common.eventhandler.EventBus$1@72bc2e
[14:48:16] [Server thread/ERROR] [FML]: 66: net.minecraftforge.fml.common.eventhandler.EventBus$1@e10718
[14:48:16] [Server thread/ERROR] [FML]: 67: net.minecraftforge.fml.common.eventhandler.EventBus$1@1fd968f
[14:48:16] [Server thread/ERROR] [FML]: 68: net.minecraftforge.fml.common.eventhandler.EventBus$1@1b53f5e
[14:48:16] [Server thread/ERROR] [FML]: 69: net.minecraftforge.fml.common.eventhandler.EventBus$1@bb734a
[14:48:16] [Server thread/ERROR] [FML]: 70: net.minecraftforge.fml.common.eventhandler.EventBus$1@e06dc2
[14:48:16] [Server thread/ERROR] [FML]: 71: net.minecraftforge.fml.common.eventhandler.EventBus$1@1a4dabf
[14:48:16] [Server thread/ERROR] [FML]: 72: net.minecraftforge.fml.common.eventhandler.EventBus$1@1dd4b9a
[14:48:16] [Server thread/ERROR] [FML]: 73: net.minecraftforge.fml.common.eventhandler.EventBus$1@255e88
[14:48:16] [Server thread/ERROR] [FML]: 74: net.minecraftforge.fml.common.eventhandler.EventBus$1@128a173
[14:48:16] [Server thread/ERROR] [FML]: 75: net.minecraftforge.fml.common.eventhandler.EventBus$1@f2eecb
[14:48:16] [Server thread/ERROR] [FML]: 76: net.minecraftforge.fml.common.eventhandler.EventBus$1@122fd94
[14:48:16] [Server thread/ERROR] [FML]: 77: net.minecraftforge.fml.common.eventhandler.EventBus$1@1bb3166
[14:48:16] [Server thread/ERROR] [FML]: 78: net.minecraftforge.fml.common.eventhandler.EventBus$1@13c215b
[14:48:16] [Server thread/ERROR] [FML]: 79: LOW
[14:48:16] [Server thread/ERROR] [FML]: 80: net.minecraftforge.fml.common.eventhandler.EventBus$1@650dc1
[14:48:16] [Server thread/ERROR] [FML]: 81: LOWEST
[14:48:16] [Server thread/ERROR] [FML]: 82: net.minecraftforge.fml.common.eventhandler.EventBus$1@a79b44
[14:48:16] [Server thread/ERROR] [FML]: 83: net.minecraftforge.fml.common.eventhandler.EventBus$1@1daef7
[14:48:16] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: net/minecraftforge/client/model/ModelLoader
        at com.beeshroom.brickery.blocks.BlockBase.register(BlockBase.java:31) ~[BlockBase.class:?]
        at com.beeshroom.brickery.blocks.BlockBase.<init>(BlockBase.java:23) ~[BlockBase.class:?]
        at com.beeshroom.brickery.blocks.BlockMossyBricks.<init>(BlockMossyBricks.java:11) ~[BlockMossyBricks.class:?]
        at com.beeshroom.brickery.init.ModBlocks.<clinit>(ModBlocks.java:32) ~[ModBlocks.class:?]
        at com.beeshroom.brickery.util.handlers.RegistryHandler.onBlockRegister(RegistryHandler.java:23) ~[RegistryHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_19_RegistryHandler_onBlockRegister_Register.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845) ~[GameData.class:?]
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:628) ~[Loader.class:?]
        at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) ~[FMLServerHandler.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.model.ModelLoader
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 16 more
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/block/model/ModelBakery
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 16 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.block.model.ModelBakery
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 16 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@15caf08 from coremod FMLCorePlugin
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 16 more
Caused by: java.lang.RuntimeException: Attempted to load class cgb for invalid side SERVER
        at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
        at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256) ~[forge-1.12.2-14.23.5.2838-universal.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_211]
        at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_211]
        ... 16 more
</details>

**Comment by JoelZBub** [comment]
Good luck getting a reply.

**Comment by DrakoAlcarus** [comment]
Just poking in again to see if you'd ever update and fix the crash. I love the mod a lot and wish I could use it with my friends.

**Comment by DrakoAlcarus** [comment]
Rip Real nice mod. Hoping we can get someone to do a pull request and make a working fork.
